:terms:
    - :id: 1
      :term: Banana
    - :id: 2
      :term: Cashews
    - :id: 3
      :term: Cassava
    - :id: 4
      :term: Cattle
    - :id: 5
      :term: Cereals
    - :id: 6
      :term: Chick Pea
    - :id: 7
      :term: Crops
    - :id: 8
      :term: Dairy
    - :id: 9
      :term: Groundnut
    - :id: 10
      :term: Large Ruminants
    - :id: 11
      :term: Legumes
    - :id: 12
      :term: Livestock
    - :id: 13
      :term: Maize
    - :id: 14
      :term: Millet
    - :id: 15
      :term: Pigeon Pea
    - :id: 16
      :term: Plantains
    - :id: 17
      :term: Poultry
    - :id: 18
      :term: Rice
    - :id: 19
      :term: Ruminants
    - :id: 20
      :term: Small Ruminants
    - :id: 21
      :term: Sorghum
    - :id: 22
      :term: Soybean
    - :id: 23
      :term: Sweet Potato
    - :id: 24
      :term: Vegetatively Propogated Crops
    - :id: 25
      :term: Wheat
    - :id: 26
      :term: Yams

