:terms:
    - :term: Annual Report
    - :term: Article
    - :term: Audio File
    - :term: Book/Book Chapter
    - :term: Commissioned Report
    - :term: Newsletter
    - :term: Photo/Image
    - :term: Presentations 
    - :term: Spreadsheet
    - :term: Strategy Document
    - :term: Technical Document
    - :term: Video File
    - :term: White Paper

