:terms:
    - :id: 1
      :term: Aggregation, Quality and Storage
    - :id: 2
      :term: Agronomic/Diagnostics
    - :id: 3
      :term: Animal Health Systems
    - :id: 4
      :term: Crop/Livestock Improvement
    - :id: 5
      :term: Discovery
    - :id: 6
      :term: End-user demand
    - :id: 7
      :term: Environment
    - :id: 8
      :term: Farm Management
    - :id: 9
      :term: Finance & Insurance
    - :id: 10
      :term: Gender
    - :id: 11
      :term: Infrastructure, transport and logistics
    - :id: 12
      :term: Input Systems
    - :id: 13
      :term: Knowledge Exchange
    - :id: 14
      :term: Livestock Production Management
    - :id: 15
      :term: Nutrition
    - :id: 16
      :term: Other Input Systems
    - :id: 17
      :term: Policies and data
    - :id: 18
      :term: Processing
    - :id: 19
      :term: Seed Systems

