default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME_PREFIX']}_development" %>
  username: <%= "#{ENV['DATABASE_RAILS_USER']}" %>
  password: <%= "#{ENV['DATABASE_RAILS_USER_PW']}" %>

test:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME_PREFIX']}_test" %>
  username: <%= "#{ENV['DATABASE_RAILS_USER']}" %>
  password: <%= "#{ENV['DATABASE_RAILS_USER_PW']}" %>

production:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME_PREFIX']}" %>
  username: <%= "#{ENV['DATABASE_RAILS_USER']}" %>
  password: <%= "#{ENV['DATABASE_RAILS_USER_PW']}" %>

